### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by ukstv** [feross/safe-buffer#20]
Hey @feross, are you open to including TypeScript type definitions in the project?

**Comment by feross** [comment]
Sure. My only reservation is who will maintain the types in the future? I don't use TypeScript myself.

**Comment by feross** [comment]
Without someone volunteering to maintain them, I'd rather have no definitions than out-of-date ones.

**Comment by ukstv** [comment]
Ok, I am the volunteer, since my stuff depends on safe-buffer.

**Comment by ukstv** [comment]
Worth reconsidering?

**Comment by feross** [comment]
Sure, want to send a pull request with the types file and I'll take a look?
