### ISSUE TITLE
[question] When do you need this?

### ISSUE THREAD

**Issue by jimmywarting** [feross/safe-buffer#24]
Is this not needed if you only target node v6 and upwards?

**Comment by lonix1** [comment]
@jimmywarting Hey Jimmy did you figure this out? I'm also wondering about that...

**Comment by jimmywarting** [comment]
no, but my assumption is if you need to support node version lower then 6 you should maybe need this lib.

**Comment by lonix1** [comment]
Yeah that's what I think - this is obsolete if you are using the latest node.

I just do

````
Buffer.from("base64string", "base64").toString("utf8");
````

**Comment by jimmywarting** [comment]
Same, same. But i try to use `Uint8Array` instead of `Buffer` whenever possible if the other functionality is not needed... Gives you a better cross browser/node/deno support and the browser bundle will be a lot smaller.

**Comment by lonix1** [comment]
Interesting... I've been using `Buffer` in my server app, and `window.atob` / `window.btoa` in my client app (angular).

**Comment by jimmywarting** [comment]
i try to avoid base64 whenever possible, base64 is roughly ~33% larger in memory/size and it takes time to compile back and forth between binary and base64. Blobs and typed arrays is a good candidate when dealing with data

For example, when i want to display an image i use `URL.createObjectURL(blob)` instead of a base64 image url

**Comment by lonix1** [comment]
Good to know, thanks!

**Comment by feross** [comment]
If you're using this package purely as a shim, then it should not be needed in Node 6 or higher since `Buffer.alloc`, etc. are built in.

**Comment by jimmywarting** [comment]
Should this be like deprecated now, feels like it have done it's part...
