### ISSUE TITLE
require('safe-buffer').Buffer is undefined

### ISSUE THREAD

**Issue by Vartex05** [feross/safe-buffer#29]
Hi, iam trying to use iconv-lite library in my ionic5 app, but when i tried to encode some string i get this error:
`core.js:6014 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'isEncoding' of undefined TypeError: Cannot read property 'isEncoding' of undefined at Object../node_modules/string_decoder/lib/string_decoder.js (string_decoder.js:29) at __webpack_require__ (bootstrap:84) at Object../node_modules/iconv-lite/encodings/internal.js (internal.js:49) at __webpack_require__ (bootstrap:84) at Object../node_modules/iconv-lite/encodings/index.js (index.js:6) at __webpack_require__ (bootstrap:84) at Object.getCodec (index.js:65) at Object.getEncoder (index.js:117) at Object.encode (index.js:22) at PrintService.testEncode (print.service.ts:26) at resolvePromise (zone-evergreen.js:797) at zone-evergreen.js:862 at ZoneDelegate.invokeTask (zone-evergreen.js:391) at Object.onInvokeTask (core.js:39680) at ZoneDelegate.invokeTask (zone-evergreen.js:390) at Zone.runTask (zone-evergreen.js:168) at drainMicroTaskQueue (zone-evergreen.js:559) at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469) at invokeTask (zone-evergreen.js:1603) at HTMLElement.globalZoneAwareCallback (zone-evergreen.js:1629)`

This looks like a problem with unknown encoding, but i call it correctly:
iconv.encode('test','cp852')

It seems that require('safe-buffer').Buffer is undefined

Any ideas why this happens? Iam using ionic 5 with angular 8.

**Comment by feross** [comment]
Perhaps your environment is not making `Buffer` available?

I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
