### ISSUE TITLE
Can it be used inside browser enviroment?

### ISSUE THREAD

**Issue by PetersonLian** [feross/safe-buffer#8]
As the title says.

**Comment by PetersonLian** [comment]
I see in `browser.js`:

    module.exports = require('buffer')
So this package depends on `buffer`. But why does this dependency not be written inside file :`packge.json`

**Comment by feross** [comment]
Yes, this package can be used inside a browser environment. When you bundle your code with browserify or webpack, calls to Node.js built-ins like `require('buffer')` will automatically be replaced with browser implementations. In this case, the implementation used is [`feross/buffer`](https://github.com/feross/buffer).

You don't need to add Node.js built-in packages to your `package.json`.

**Comment by PetersonLian** [comment]
@feross 
Now I see: the bundle tool does the magic. 
Thanks.
