### ISSUE TITLE
can load an old version of buffer

### ISSUE THREAD

**Issue by calvinmetcalf** [feross/safe-buffer#9]
from [an issue in pbkdf2](https://github.com/crypto-browserify/createHmac/issues/20#issuecomment-300964249)

> I think one of the issues is that safe-buffer requires the buffer package however since buffer is not specified in the safe-buffer package.json there's no constraint on the version that will satisfy it. So if another package is already using an older buffer release then safe-buffer won't pull a later one. Some of the older buffer packages releases do not support alloc.

**Comment by dcousens** [comment]
I think the point is that `Buffer` **should** remain unconstrained - with browserify opting for `buffer` the dependency.

**Comment by feross** [comment]
This was fixed by #12 and released as 5.1.0.
